# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61723cce552fc6a26e0813db9f5b34d90b452aeea152b64395ed776c3f8f099937e1e5de3085b13df938b2a9f5216fd2a661a205a11d96b0849d54237ea749f8

test:
  secret_key_base: c97405f2d8a7f7911a51ce5035835abf85c30c2ed0e1d6834f0e2c97fc475ba01dbc1130422d491c5ef6b7ab6628475a5ab5aebb2950dad211e4cf47858f4c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
