# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2668519eb1f8bdf0af2b4cb4c0d30ed0d19041cf937ebbc0807252b5300db185e9b9175b27a82989931915cc08e6c04838bf4ea871efe1ab1465a5e1ef8eab6f

test:
  secret_key_base: c3111f7496c8831e5afa3d876e5eb0ecdb1d0b5f9cede05e0edf8863175798a9cc60d1c185466146e810bf9c3c4f368deaeea5f47095fab97097c21eebc1d7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
