# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7101c0081cd5ca80f8216653cd34886406b587b1825caba2c431b3b2c905a3136350cb74aee5f88b684bea08324fc8b78b6109581bb4e09a16e0bdd24dde581

test:
  secret_key_base: e93be2bedaca940bbc48157d1f01282dad777f79f037ad453679a868da333a95387b719bd34173104128cc8ae068299a9068e1a56468387752aa7abfa69fe4ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
