# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa76f60314cb394d69cca5dc8b9a6952fee99378c940f3d7b1eb40d390363f88274c69f38aa23e768b873429bbf87c31954530a5a3faf10de74b30a47c41f850

test:
  secret_key_base: 65bfb1c7b6e7de09c9602c57918e62b814b3e90fc8e7811777b7a03cf7e2ffac76ee22004b17a3ba2f1be555471ad6b3aedf1f26b09f80a6f137a332b8fb4720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
